----------- CUSTOMER TABLE 

CREATE TABLE CUSTOMER(CUSTOMER_ID NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 PRIMARY KEY,
                      CUSTOMER_NAME VARCHAR(20),
                      GENDER VARCHAR(1),
                      DOB DATE, 
                      CITY VARCHAR(20)
                      );





----------- ACCOUNT TABLE 

CREATE TABLE ACCOUNT(ACCOUNT_ID NUMBER GENERATED ALWAYS AS IDENTITY START WITH 11 PRIMARY KEY, 
                     CUSTOMER_ID NUMBER REFERENCES CUSTOMER(CUSTOMER_ID), 
                     ACCOUNT_TYPE VARCHAR(2) CHECK(ACCOUNT_TYPE IN('SA','CA','FD','RD')), 
                     OPEN_DATE DATE, 
                     BALANCE NUMBER
                     );





----------- BRANCH TABLE

CREATE TABLE BRANCH(BRANCH_ID NUMBER GENERATED ALWAYS AS IDENTITY START WITH 101 PRIMARY KEY,
                    BRANCH_NAME VARCHAR(20), 
                    CITY VARCHAR(20)
                    );





---------------- BANK_TRANSACTION TABLE

CREATE TABLE BANK_TRANSACTION (TRANSACTION_ID NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1001 PRIMARY KEY,
                               CUSTOMER_ID NUMBER REFERENCES CUSTOMER(CUSTOMER_ID),
                               ACCOUNT_ID NUMBER REFERENCES ACCOUNT(ACCOUNT_ID),
                               BRANCH_ID NUMBER REFERENCES BRANCH(BRANCH_ID),
                               TRANSACTION_DATE DATE,
                               TRANSACTION_TYPE VARCHAR2(20)CHECK (TRANSACTION_TYPE IN ('Deposit', 'Withdrawal','Transfer')),
                               AMOUNT NUMBER
                               );



SELECT * FROM CUSTOMER;
SELECT * FROM ACCOUNT;
SELECT * FROM BRANCH;
SELECT * FROM BANK_TRANSACTION;

DROP TABLE CUSTOMER;
DROP TABLE ACCOUNT;
DROP TABLE BRANCH;
DROP TABLE BANK_TRANSACTION;