----------- CUSTOMER TABLE 

INSERT INTO CUSTOMER(CUSTOMER_NAME,GENDER,DOB,CITY) VALUES('RAKHI','F',TO_DATE('08-AUG-2005', 'DD-MON-YYYY'),'BADLAPUR');
INSERT INTO CUSTOMER(CUSTOMER_NAME,GENDER,DOB,CITY) VALUES('SHRUI','F',TO_DATE('09-AUG-2005', 'DD-MON-YYYY'),'GHATKOPAR');
INSERT INTO CUSTOMER(CUSTOMER_NAME,GENDER,DOB,CITY) VALUES('TANVI','F',TO_DATE('10-AUG-2005', 'DD-MON-YYYY'),'MURBAD');
INSERT INTO CUSTOMER(CUSTOMER_NAME,GENDER,DOB,CITY) VALUES('PRACHI','F',TO_DATE('11-AUG-2005', 'DD-MON-YYYY'),'BADLAPUR');
INSERT INTO CUSTOMER(CUSTOMER_NAME,GENDER,DOB,CITY) VALUES('SURESH','M',TO_DATE('12-AUG-2005', 'DD-MON-YYYY'),'BADLAPUR');
INSERT INTO CUSTOMER(CUSTOMER_NAME,GENDER,DOB,CITY) VALUES('SUREKHA','F',TO_DATE('13-AUG-2005', 'DD-MON-YYYY'),'BADLAPUR');
INSERT INTO CUSTOMER(CUSTOMER_NAME,GENDER,DOB,CITY) VALUES('BHUSHAN','M',TO_DATE('14-AUG-2005', 'DD-MON-YYYY'),'BADLAPUR');
INSERT INTO CUSTOMER(CUSTOMER_NAME,GENDER,DOB,CITY) VALUES('ANIRUDHA','M',TO_DATE('15-AUG-2005', 'DD-MON-YYYY'),'BADLAPUR');
INSERT INTO CUSTOMER(CUSTOMER_NAME,GENDER,DOB,CITY) VALUES('PRADEEP','M',TO_DATE('16-AUG-2005', 'DD-MON-YYYY'),'AMBIVLI');
INSERT INTO CUSTOMER(CUSTOMER_NAME,GENDER,DOB,CITY) VALUES('SUMIT','M',TO_DATE('17-AUG-2005', 'DD-MON-YYYY'),'MALKAPUR');
INSERT INTO CUSTOMER(CUSTOMER_NAME,GENDER,DOB,CITY) VALUES('OMKAR','M',TO_DATE('18-AUG-2005', 'DD-MON-YYYY'),'AMBERNATH');
INSERT INTO CUSTOMER(CUSTOMER_NAME,GENDER,DOB,CITY) VALUES('VAISHNAVI','F',TO_DATE('19-AUG-2005', 'DD-MON-YYYY'),'AMBERNATH');
INSERT INTO CUSTOMER(CUSTOMER_NAME,GENDER,DOB,CITY) VALUES('SOUMYA','F',TO_DATE('20-AUG-2005', 'DD-MON-YYYY'),'AMBERNATH');
INSERT INTO CUSTOMER(CUSTOMER_NAME,GENDER,DOB,CITY) VALUES('GAURAV','M',TO_DATE('21-AUG-2005', 'DD-MON-YYYY'),'ULHASNAGAR');
INSERT INTO CUSTOMER(CUSTOMER_NAME,GENDER,DOB,CITY) VALUES('MAYUR','M',TO_DATE('22-AUG-2005', 'DD-MON-YYYY'),'PANVEL');
INSERT INTO CUSTOMER(CUSTOMER_NAME,GENDER,DOB,CITY) VALUES('MADHURA','F',TO_DATE('23-AUG-2005', 'DD-MON-YYYY'),'MALKAPUR');


----------- ACCOUNT TABLE 

INSERT INTO ACCOUNT(CUSTOMER_ID,ACCOUNT_TYPE,OPEN_DATE,BALANCE) VALUES(1,'SA',TO_DATE('01-JAN-2024','DD-MON-YYYY'),50000);
INSERT INTO ACCOUNT(CUSTOMER_ID,ACCOUNT_TYPE,OPEN_DATE,BALANCE) VALUES(1,'CA',TO_DATE('02-JAN-2024','DD-MON-YYYY'),12000);
INSERT INTO ACCOUNT(CUSTOMER_ID,ACCOUNT_TYPE,OPEN_DATE,BALANCE) VALUES(5,'FD',TO_DATE('03-JAN-2024','DD-MON-YYYY'),60000);
INSERT INTO ACCOUNT(CUSTOMER_ID,ACCOUNT_TYPE,OPEN_DATE,BALANCE) VALUES(6,'RD',TO_DATE('04-JAN-2024','DD-MON-YYYY'),40000);
INSERT INTO ACCOUNT(CUSTOMER_ID,ACCOUNT_TYPE,OPEN_DATE,BALANCE) VALUES(2,'SA',TO_DATE('05-JAN-2024','DD-MON-YYYY'),50000);
INSERT INTO ACCOUNT(CUSTOMER_ID,ACCOUNT_TYPE,OPEN_DATE,BALANCE) VALUES(5,'CA',TO_DATE('06-JAN-2024','DD-MON-YYYY'),17000);
INSERT INTO ACCOUNT(CUSTOMER_ID,ACCOUNT_TYPE,OPEN_DATE,BALANCE) VALUES(7,'FD',TO_DATE('07-JAN-2024','DD-MON-YYYY'),70000);
INSERT INTO ACCOUNT(CUSTOMER_ID,ACCOUNT_TYPE,OPEN_DATE,BALANCE) VALUES(8,'RD',TO_DATE('08-JAN-2024','DD-MON-YYYY'),30000);
INSERT INTO ACCOUNT(CUSTOMER_ID,ACCOUNT_TYPE,OPEN_DATE,BALANCE) VALUES(3,'SA',TO_DATE('09-JAN-2024','DD-MON-YYYY'),20000);
INSERT INTO ACCOUNT(CUSTOMER_ID,ACCOUNT_TYPE,OPEN_DATE,BALANCE) VALUES(9,'CA',TO_DATE('01-FEB-2024','DD-MON-YYYY'),5000);
INSERT INTO ACCOUNT(CUSTOMER_ID,ACCOUNT_TYPE,OPEN_DATE,BALANCE) VALUES(10,'FD',TO_DATE('03-FEB-2024','DD-MON-YYYY'),70000);
INSERT INTO ACCOUNT(CUSTOMER_ID,ACCOUNT_TYPE,OPEN_DATE,BALANCE) VALUES(11,'RD',TO_DATE('03-FEB-2024','DD-MON-YYYY'),20000);
INSERT INTO ACCOUNT(CUSTOMER_ID,ACCOUNT_TYPE,OPEN_DATE,BALANCE) VALUES(4,'SA',TO_DATE('04-FEB-2024','DD-MON-YYYY'),5000);
INSERT INTO ACCOUNT(CUSTOMER_ID,ACCOUNT_TYPE,OPEN_DATE,BALANCE) VALUES(12,'CA',TO_DATE('05-FEB-2024','DD-MON-YYYY'),50000);
INSERT INTO ACCOUNT(CUSTOMER_ID,ACCOUNT_TYPE,OPEN_DATE,BALANCE) VALUES(13,'FD',TO_DATE('06-FEB-2024','DD-MON-YYYY'),40000);
INSERT INTO ACCOUNT(CUSTOMER_ID,ACCOUNT_TYPE,OPEN_DATE,BALANCE) VALUES(21,'FD',TO_DATE('07-FEB-2024','DD-MON-YYYY'),20000);


----------- BRANCH TABLE

INSERT INTO BRANCH(BRANCH_NAME,CITY) VALUES('B1','BADLAPUR');
INSERT INTO BRANCH(BRANCH_NAME,CITY) VALUES('B2','AMBERNATH');
INSERT INTO BRANCH(BRANCH_NAME,CITY) VALUES('B3','GHATKOPAR');
INSERT INTO BRANCH(BRANCH_NAME,CITY) VALUES('B4','AMBIVLI');
INSERT INTO BRANCH(BRANCH_NAME,CITY) VALUES('B5','MALKAPUR');
INSERT INTO BRANCH(BRANCH_NAME,CITY) VALUES('B6','ULHASNAGAR');

---------------- BANK_TRANSACTION TABLE

                  
INSERT INTO BANK_TRANSACTION (CUSTOMER_ID, ACCOUNT_ID, BRANCH_ID, TRANSACTION_DATE, TRANSACTION_TYPE, AMOUNT)
VALUES (1, 11, 101, TO_DATE('10-MAR-2024','DD-MON-YYYY'), 'Deposit', 5000);

INSERT INTO BANK_TRANSACTION (CUSTOMER_ID, ACCOUNT_ID, BRANCH_ID, TRANSACTION_DATE, TRANSACTION_TYPE, AMOUNT)
VALUES (1, 12, 101, TO_DATE('12-MAR-2024','DD-MON-YYYY'), 'Withdrawal', 2000);

INSERT INTO BANK_TRANSACTION (CUSTOMER_ID, ACCOUNT_ID, BRANCH_ID, TRANSACTION_DATE, TRANSACTION_TYPE, AMOUNT)
VALUES (5, 13, 102, TO_DATE('15-MAR-2024','DD-MON-YYYY'), 'Deposit', 10000);

INSERT INTO BANK_TRANSACTION (CUSTOMER_ID, ACCOUNT_ID, BRANCH_ID, TRANSACTION_DATE, TRANSACTION_TYPE, AMOUNT)
VALUES (6, 14, 103, TO_DATE('18-MAR-2024','DD-MON-YYYY'), 'Withdrawal', 1500);

INSERT INTO BANK_TRANSACTION (CUSTOMER_ID, ACCOUNT_ID, BRANCH_ID, TRANSACTION_DATE, TRANSACTION_TYPE, AMOUNT)
VALUES (2, 15, 103, TO_DATE('20-MAR-2024','DD-MON-YYYY'), 'Transfer', 3000);

INSERT INTO BANK_TRANSACTION (CUSTOMER_ID, ACCOUNT_ID, BRANCH_ID, TRANSACTION_DATE, TRANSACTION_TYPE, AMOUNT)
VALUES (5, 16, 104, TO_DATE('22-MAR-2024','DD-MON-YYYY'), 'Deposit', 7000);

INSERT INTO BANK_TRANSACTION (CUSTOMER_ID, ACCOUNT_ID, BRANCH_ID, TRANSACTION_DATE, TRANSACTION_TYPE, AMOUNT)
VALUES (7, 17, 105, TO_DATE('25-MAR-2024','DD-MON-YYYY'), 'Withdrawal', 4000);

INSERT INTO BANK_TRANSACTION (CUSTOMER_ID, ACCOUNT_ID, BRANCH_ID, TRANSACTION_DATE, TRANSACTION_TYPE, AMOUNT)
VALUES (8, 18, 101, TO_DATE('28-MAR-2024','DD-MON-YYYY'), 'Transfer', 2500);

INSERT INTO BANK_TRANSACTION (CUSTOMER_ID, ACCOUNT_ID, BRANCH_ID, TRANSACTION_DATE, TRANSACTION_TYPE, AMOUNT)
VALUES (3, 19, 102, TO_DATE('30-MAR-2024','DD-MON-YYYY'), 'Deposit', 6000);

INSERT INTO BANK_TRANSACTION (CUSTOMER_ID, ACCOUNT_ID, BRANCH_ID, TRANSACTION_DATE, TRANSACTION_TYPE, AMOUNT)
VALUES (9, 20, 106, TO_DATE('02-APR-2024','DD-MON-YYYY'), 'Withdrawal', 1000);

INSERT INTO BANK_TRANSACTION (CUSTOMER_ID, ACCOUNT_ID, BRANCH_ID, TRANSACTION_DATE, TRANSACTION_TYPE, AMOUNT)
VALUES (10, 21, 104, TO_DATE('05-APR-2024','DD-MON-YYYY'), 'Deposit', 12000);

INSERT INTO BANK_TRANSACTION (CUSTOMER_ID, ACCOUNT_ID, BRANCH_ID, TRANSACTION_DATE, TRANSACTION_TYPE, AMOUNT)
VALUES (11, 22, 105, TO_DATE('08-APR-2024','DD-MON-YYYY'), 'Transfer', 3500);

INSERT INTO BANK_TRANSACTION (CUSTOMER_ID, ACCOUNT_ID, BRANCH_ID, TRANSACTION_DATE, TRANSACTION_TYPE, AMOUNT)
VALUES (4, 23, 101, TO_DATE('10-APR-2024','DD-MON-YYYY'), 'Deposit', 4500);

INSERT INTO BANK_TRANSACTION (CUSTOMER_ID, ACCOUNT_ID, BRANCH_ID, TRANSACTION_DATE, TRANSACTION_TYPE, AMOUNT)
VALUES (12, 24, 102, TO_DATE('12-APR-2024','DD-MON-YYYY'), 'Withdrawal', 2200);

INSERT INTO BANK_TRANSACTION (CUSTOMER_ID, ACCOUNT_ID, BRANCH_ID, TRANSACTION_DATE, TRANSACTION_TYPE, AMOUNT)
VALUES (13, 25, 106, TO_DATE('15-APR-2024','DD-MON-YYYY'), 'Deposit', 8000);